[package]
name = "linguify_fluent_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ciborium = "0.2.2"
fluent = "0.16.0"
fluent-syntax = "0.11.0"
serde = { version = "1.0.213", features = ["derive"] }
unic-langid = "0.9.4"
wasm-minimal-protocol = "0.1.0"
